config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parkings
  root "parkings#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :user
  validates :parking_type, presence:true 
  validates :start_at, presence:true 
  validates_inclusion_of :parking_type, in: ["guest", "short-term", "long-term"]

  validate :validate_end_at_with_amount

  def validate_end_at_with_amount
    if ( end_at.present? && amount.blank? )
        errors.add(:amount, "有结束时间就必须有金额")
    end
      
    if ( end_at.blank? && amount.present? )
      errors.add(:end_at, "有金额就必须有结束时间")
    end
  end

  # 计算停了多少分钟
  def duration
    (end_at - start_at) / 60
  end

  # 计算停车费
  def calculate_amount 
    factor = (self.user.present?)? 50 : 100
    if self.amount.blank? && self.start_at.present? && self.end_at.present?
      if duration <= 60
        self.amount = 200
      else
        self.amount = 200 + ((duration - 60).to_f / 30).ceil * factor
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :parkings, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
    # Step1: 显示开始停车的表单
   def new
     @parking = Parking.new
   end

   # Step2: 新建一笔停车，纪录下开始时间
   def create
     @parking = Parking.new(start_at: Time.now )
     if current_user 
      @parking.parking_type = params[:parking][:parking_type]
      @parking.user = current_user
     else
      @parking.parking_type = "guest"
     end

     @parking.save!
     redirect_to parking_path(@parking)
   end

   # Step3: 如果还没结束，显示结束停车的表单
   # Step5: 如果已经结束，显示停车费用。
   def show
     @parking = Parking.find(params[:id])
   end

   # Step4: 结束一笔停车，记录下结束时间，并且计算停车费
   def update
     @parking = Parking.find(params[:id])
     @parking.end_at = Time.now
     @parking.calculate_amount

     @parking.save!

     redirect_to parking_path(@parking)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% if flash[:notice] %>
     <%= flash[:notice] %>
   <% end %>

   <% if flash[:alert] %>
     <%= flash[:alert] %>
   <% end %>

  <% if current_user %>
     <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
    <%= link_to('修改密码', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('注册', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
   <% end %>
    <%= yield %>
  </body>
</html>

app/views/parkings/new.html.erb
<h1>停车费用计算</h1>

<%= form_for @parking do |f| %>
    <% if current_user %>

    <label>
      <%= f.radio_button :parking_type, "short-term" %> 短期费率
    </label>

    <label>
      <%= f.radio_button :parking_type, "long-term" %> 长期费率
    </label>

  <% else %>
    一般费率
  <% end %>

  <p><%= f.submit "开始计费" %></p>
<% end %>

app/views/parkings/show.html.erb
<h1>停车费用计算</h1>

<% if @parking.amount.present? # 已经结束，显示停车费 %>
  <p>计费方式 <%= @parking.parking_type %></p>

  <p>从 <%= @parking.start_at %> 至 <%= @parking.end_at %><p>
  <p>共 <%= @parking.duration %> 分钟</p>
  <p>总计 <%= number_to_currency(@parking.amount.to_f / 100, :unit => "¥") %> 元</p>

  <p><%= link_to "继续停车", new_parking_path %></p>

<% else # 还没结束，显示结束按钮 %>

  <%= form_for @parking do |f| %>

    <p><%= f.submit "结束计费" %></p>

  <% end %>

<% end %>